name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: yaara-art-studio/package-lock.json
        
    - name: Install dependencies
      run: |
        cd yaara-art-studio
        npm ci
        
    - name: Build Angular app
      run: |
        cd yaara-art-studio
        npm run build:github-pages
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: yaara-art-studio/dist/yaara-art-studio/browser
        cname: # Add your custom domain here if you have one
